# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Z < Formula
  desc "Personal ops console"
  homepage "https://github.com/Zenku-App/homebrew-z"
  version "2026.4.1"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Zenku-App/homebrew-z/releases/download/v2026.4.1/z_2026.4.1_darwin_arm64.tar.gz"
    sha256 "d65ee73d5b819906a345c858af1cab16e1d831e8fbff17e86cc35c9c6cb109f9"

    define_method(:install) do
      bin.install "z"
    end
  end

  test do
    assert_predicate bin/"z", :executable?
  end
end
