# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZepServer < Formula
  desc "Personal ops console (operator/server build)"
  homepage "https://github.com/Zenku-App/homebrew-zep"
  version "2026.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.5.1/zep-server_2026.5.1_darwin_amd64.tar.gz"
      sha256 "d5e7f1f666527252d9b4c39ffe733b718e9ff14140f57b9a27949ee911d36c58"

      define_method(:install) do
        bin.install "zep-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.5.1/zep-server_2026.5.1_darwin_arm64.tar.gz"
      sha256 "b011ce72241bf1f3bab6df4823b8951a10253f2721f13a8caa30a1af4f302646"

      define_method(:install) do
        bin.install "zep-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.5.1/zep-server_2026.5.1_linux_amd64.tar.gz"
      sha256 "eb2b6699d9fcc57a9016821c2fb670307bb02799d3c1fd78134bd89b6162b2e6"
      define_method(:install) do
        bin.install "zep-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.5.1/zep-server_2026.5.1_linux_arm64.tar.gz"
      sha256 "400f7a2497f17bfd5e856c7263e2b670e1f3da68e3cf16bbd35c3fa25f49c88c"
      define_method(:install) do
        bin.install "zep-server"
      end
    end
  end

  test do
    assert_predicate bin/"zep-server", :executable?
  end
end
