# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZepServer < Formula
  desc "Personal ops console (operator/server build)"
  homepage "https://github.com/Zenku-App/homebrew-zep"
  version "2026.6.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.23/zep-server_2026.6.23_darwin_amd64.tar.gz"
      sha256 "cf4d6b9bb06dbf94b92fb917ae4b986124d805d6a47d4b0df73f309443b30b34"

      define_method(:install) do
        bin.install "zep-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.23/zep-server_2026.6.23_darwin_arm64.tar.gz"
      sha256 "a632260a135efcce8f4af27435f58708b7cb46958a4fe3377c169f6641e4e339"

      define_method(:install) do
        bin.install "zep-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.23/zep-server_2026.6.23_linux_amd64.tar.gz"
      sha256 "23602d766b49f2e32ea299d88d9a8c6af9b1ca3452ec78c9da43ff0970168ad4"
      define_method(:install) do
        bin.install "zep-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.23/zep-server_2026.6.23_linux_arm64.tar.gz"
      sha256 "a8eda5427b585b74de3c56739ccc68d1f011d737cce10b0f80c408133af09209"
      define_method(:install) do
        bin.install "zep-server"
      end
    end
  end

  test do
    assert_predicate bin/"zep-server", :executable?
  end
end
