# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZepDesktop < Formula
  desc "Personal ops console"
  homepage "https://github.com/Zenku-App/homebrew-zep"
  version "2026.6.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.13/zep-desktop_2026.6.13_darwin_amd64.tar.gz"
      sha256 "1cdf783ed8a9ab3cb7f988bcc0ffb61e701b77c8e5c36cf599ba23b0faa89bdb"

      define_method(:install) do
        bin.install "zep-desktop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.13/zep-desktop_2026.6.13_darwin_arm64.tar.gz"
      sha256 "aba3d7175654506b58848feca955e02775652e6fc1236b05895f0fd96f31c7d3"

      define_method(:install) do
        bin.install "zep-desktop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.13/zep-desktop_2026.6.13_linux_amd64.tar.gz"
      sha256 "25a6d882be32203afc05a2ea72b3d048a7afdb0b9471d500191602ca4c075943"
      define_method(:install) do
        bin.install "zep-desktop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.13/zep-desktop_2026.6.13_linux_arm64.tar.gz"
      sha256 "ae75a1705465ea97d7983827bb5562db1c9289a3591351d7484cbc94ce5d3361"
      define_method(:install) do
        bin.install "zep-desktop"
      end
    end
  end

  test do
    assert_predicate bin/"zep-desktop", :executable?
  end
end
