# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZepServer < Formula
  desc "Personal ops console (operator/server build)"
  homepage "https://github.com/Zenku-App/homebrew-zep"
  version "2026.6.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.15/zep-server_2026.6.15_darwin_amd64.tar.gz"
      sha256 "47ef26f55ff4193bc4948918d249cc3b29392b91e2032b1bfa878d1f0e4ff41d"

      define_method(:install) do
        bin.install "zep-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.15/zep-server_2026.6.15_darwin_arm64.tar.gz"
      sha256 "2ebf666a9feda6f0098f6be57b266e4ee3b94ee1876f7912fa15a8acd3b580d8"

      define_method(:install) do
        bin.install "zep-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.15/zep-server_2026.6.15_linux_amd64.tar.gz"
      sha256 "85798eb02e7eab4a7378b8f581966c6883800429e77fcf3c7c408b083e7b3b27"
      define_method(:install) do
        bin.install "zep-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.6.15/zep-server_2026.6.15_linux_arm64.tar.gz"
      sha256 "b2f1e1c057146bb2fd46f8e079b14e2a4045a24b808303bbcc41dce89aca86cd"
      define_method(:install) do
        bin.install "zep-server"
      end
    end
  end

  test do
    assert_predicate bin/"zep-server", :executable?
  end
end
