# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZepDesktop < Formula
  desc "Personal ops console"
  homepage "https://github.com/Zenku-App/homebrew-zep"
  version "2026.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.5.1/zep-desktop_2026.5.1_darwin_amd64.tar.gz"
      sha256 "e1d3a2d9296f8456bedce69e4fe9ff4306acb554dc6beab064d354f02f6d07e3"

      define_method(:install) do
        bin.install "zep-desktop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.5.1/zep-desktop_2026.5.1_darwin_arm64.tar.gz"
      sha256 "4b3851464419d8b6d623053cf3958bf90d86f7f952833932e2c9e19072738e90"

      define_method(:install) do
        bin.install "zep-desktop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.5.1/zep-desktop_2026.5.1_linux_amd64.tar.gz"
      sha256 "bbd7b91f2630374724933944ef8cd4c92da589d9d32b9a4379653e6754b526b7"
      define_method(:install) do
        bin.install "zep-desktop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.5.1/zep-desktop_2026.5.1_linux_arm64.tar.gz"
      sha256 "8f55f5af9bf0529cce9f48adc2e92dacd642837a78275009c896fa49d9f392be"
      define_method(:install) do
        bin.install "zep-desktop"
      end
    end
  end

  test do
    assert_predicate bin/"zep-desktop", :executable?
  end
end
