# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zep < Formula
  desc "Personal ops console"
  homepage "https://github.com/Zenku-App/homebrew-z"
  version "2026.4.2"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Zenku-App/homebrew-z/releases/download/v2026.4.2/zep_2026.4.2_darwin_arm64.tar.gz"
    sha256 "281a952f514f7d830b2cd3adbadb28873a632fbb43a00850198457cec0804161"

    define_method(:install) do
      bin.install "zep"
    end
  end

  test do
    assert_predicate bin/"zep", :executable?
  end
end
