# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zep < Formula
  desc "Personal ops console"
  homepage "https://github.com/Zenku-App/homebrew-zep"
  version "2026.4.4"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Zenku-App/homebrew-zep/releases/download/v2026.4.4/zep_2026.4.4_darwin_arm64.tar.gz"
    sha256 "ec18164607008a8dd7295a5a3382a0dc32b1fc8a9906ff8966f55007472d747d"

    define_method(:install) do
      bin.install "zep"
    end
  end

  test do
    assert_predicate bin/"zep", :executable?
  end
end
